server:
  port: 9999
  servlet:
    context-path: /auth
logging:
  level:
    cn.swunlp.*: warn
spring:
  data:
    redis:
      host: 192.168.0.88
      port: 26379
      password: 3ycieqF5o30uQHZ
  cloud:
    nacos:
      discovery:
        username: test_service
        password: mC5KCw5PYFnQJ2V
        server-addr: 192.168.0.9:8848
        group: DEV
        namespace: 1f84f72e-a565-441a-b1cb-a3c71a94431e
  application:
    name: authService